[project]
name = "dltype"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pydantic>=2.0", 
    "torch>=1.4.0",
]

[dependency-groups]
dev = [
    "onnx>=1.18.0",
    "pytest>=8.4.1",
    "ruff>=0.12.0",
]
 