name: Enforce Unit Tests

on:
  pull_request:
    branches:
      - main # or master
  push:
    branches:
      - main # or master

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.7.17

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ruff check
        run: |
          uv run ruff format --check
          uv run ruff check

      - name: Run tests
        run: |
          uv run pytest

      - name: Run benchmarks
        run: |
          uv run benchmark.py

      - name: Run type checking
        run: uv run pyright --stats
